Raise nginx client_max_body_size and make it configurable
Otherwise pushes over HTTPS, which were larger than the
default max body size (2MB) were failing with an error like this:

> error: RPC failed; HTTP 413 curl 22 The requested URL returned error: 413